try {
  let objeto = {};
  console.log(objeto.c.a)
} catch (error) {
  console.log()
} finally {
  console.log('finally');
}
